# runs testing on push and pull request of all branches
name: Test
on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  # setup node and run test script
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test